/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Froms;

import com.squareup.okhttp.FormEncodingBuilder;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.RequestBody;
import com.squareup.okhttp.Response;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class Lista extends javax.swing.JFrame {
    private Principal p;
    private String pathImg = "";
    public static OkHttpClient webClient = new OkHttpClient();
    /**
     * Creates new form Lista
     * @param p
     */
    public Lista(Principal p) {
        this.p = p;
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAgregar = new javax.swing.JTextField();
        txtborrar = new javax.swing.JTextField();
        txtbuscar = new javax.swing.JTextField();
        jbagregar = new javax.swing.JButton();
        jbborrar = new javax.swing.JButton();
        jbbuscar = new javax.swing.JButton();
        labelReporte = new javax.swing.JLabel();
        recargar = new javax.swing.JButton();
        generar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrado(evt);
            }
        });

        txtAgregar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtAgregar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtborrar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtborrar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtbuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtbuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbagregar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbagregar.setText("Agregar");
        jbagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagregarActionPerformed(evt);
            }
        });

        jbborrar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbborrar.setText("Borrar");
        jbborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbborrarActionPerformed(evt);
            }
        });

        jbbuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbbuscar.setText("Buscar");
        jbbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbuscarActionPerformed(evt);
            }
        });

        recargar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        recargar.setText("Recargar Img");
        recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarActionPerformed(evt);
            }
        });

        generar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        generar.setText("generar Img");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(generar)
                        .addGap(18, 18, 18)
                        .addComponent(recargar)
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jbbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(recargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagregarActionPerformed
        // TODO add your handling code here:
        if(!txtAgregar.getText().equals("")){
            RequestBody rb = new FormEncodingBuilder()
                .add("dato", txtAgregar.getText())
                .build();
            String print = getString("agregarSimple", rb);
            //System.out.println(print);
            txtAgregar.setText("");
            
                    RequestBody rb2 = new FormEncodingBuilder()
                    .add("dato", "unico")
                    .build();
            String recorrido = getString("recorrerSimple", rb2);
            String pathTxt = generarTxt("listaSimple", recorrido);
            pathImg = generarImagen(pathTxt, "listaSimple");
            
            JOptionPane.showMessageDialog(null, "palabra " + print + " agregado");
            //Metodos.eliminar_image_txt(pathTxt, pathImg);
        }
    }//GEN-LAST:event_jbagregarActionPerformed

    private void cerrado(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrado
        // TODO add your handling code here:
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_cerrado

    private void jbbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbuscarActionPerformed
        // TODO add your handling code here:
        if(!txtbuscar.getText().equals("")){
            RequestBody rb = new FormEncodingBuilder()
                .add("dato", txtbuscar.getText())
                .build();
            String print = getString("buscarSimple", rb);
            txtbuscar.setText("");
            if(print.equals("None")){
                System.out.println("NO SE ENCONTRO EL DATO");
            }else{
                System.out.println("EL DATO SE ENCUENTRA EN EL INDICE <" + print + ">");
            }
        }
    }//GEN-LAST:event_jbbuscarActionPerformed

    private void jbborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbborrarActionPerformed
        // TODO add your handling code here:
        if(!txtborrar.getText().equals("")){
            RequestBody rb = new FormEncodingBuilder()
                .add("dato", txtborrar.getText())
                .build();
            String print = getString("removeSimple", rb);
            if(print.equals("None")){
                System.out.println("NO SE ENCONTRO EL DATO A ELIMINAR");
            }else{
                System.out.println("EL DATO EN EL INDICE, VALOR <"+ txtborrar.getText()+ ", " + print + ">" + "HA SIDO ELIMINADO");
            }
            txtborrar.setText("");
        }
    }//GEN-LAST:event_jbborrarActionPerformed

    private void recargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarActionPerformed
        // TODO add your handling code here:
            labelReporte.setIcon(new ImageIcon(Metodos.icono(pathImg, labelReporte.getWidth(), labelReporte.getHeight())));
            labelReporte.setIcon(new ImageIcon(Metodos.icono(pathImg, labelReporte.getWidth(), labelReporte.getHeight())));
                        
//            System.out.println(recorrido);
    }//GEN-LAST:event_recargarActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        RequestBody rb2 = new FormEncodingBuilder()
                    .add("dato", "unico")
                    .build();
            String recorrido = getString("recorrerSimple", rb2);
            String pathTxt = generarTxt("listaSimple", recorrido);
            pathImg = generarImagen(pathTxt, "listaSimple");
            System.out.println(recorrido);
    }//GEN-LAST:event_generarActionPerformed

    public static String getString(String metodo, RequestBody formBody) {

        try {
            URL url = new URL("http://127.0.0.1:5000/" + metodo);
            Request request = new Request.Builder().url(url).post(formBody).build();
            Response response = webClient.newCall(request).execute();//Aqui obtiene la respuesta en dado caso si hayas pues un return en python
            String response_string = response.body().string();//y este seria el string de las respuesta
            return response_string;
        } catch (MalformedURLException ex) {
            //java.util.logging.Logger.getLogger(.log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //java.util.logging.Logger.getLogger(testwebserver.TestWebServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    
    public String generarTxt(String path, String in){
        File f = new File("C:\\txtDot\\" + path + ".txt");//"C:\\Users\\usuario\\Desktop\\ejemplo.txt");//, nodos + "}");
        try{
                FileWriter fw = new FileWriter(f, false);
                BufferedWriter br = new BufferedWriter(fw);
                br.write(in);
                br.close();
                fw.close();
        }catch(Exception e){
            
        }
        return f.getPath();
    }
    
    public String generarImagen(String pathTxt, String nombreImg){
        String pathImagen = "";
        try{
            String dopath = "C:\\release\\bin\\dot.exe";
            String architxt = pathTxt; //"C:\\txtDot\\" + path + ".txt";//path;//"C:\\Users\\usuario\\Desktop\\ejemplo.txt";
            pathImagen = "C:\\imgDot\\" + nombreImg + ".png";
            String parpng = "-Tpng";
            String paro = "-o";
               
            String cmd[] = new String[5];
            cmd[0] = dopath;
            cmd[1] = parpng;
            cmd[2] = architxt;
            cmd[3] = paro;
            cmd[4] = pathImagen;
              
            Runtime rt = Runtime.getRuntime();
            rt.exec(cmd);
        }catch(Exception e){
            System.out.println(e.toString());
        }
        return pathImagen;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar;
    private javax.swing.JButton jbagregar;
    private javax.swing.JButton jbborrar;
    private javax.swing.JButton jbbuscar;
    private javax.swing.JLabel labelReporte;
    private javax.swing.JButton recargar;
    private javax.swing.JTextField txtAgregar;
    private javax.swing.JTextField txtborrar;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
}
