/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Froms;

import com.squareup.okhttp.FormEncodingBuilder;
import com.squareup.okhttp.RequestBody;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class MatrizDispersa extends javax.swing.JFrame {
    private String pathImg = "";
    private Principal p;
    /**
     * Creates new form MatrizDispersa
     * @param p
     */
    public MatrizDispersa(Principal p) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MatrizDispersa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MatrizDispersa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MatrizDispersa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MatrizDispersa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbeliminar = new javax.swing.JButton();
        jbagregar = new javax.swing.JButton();
        btnletra = new javax.swing.JButton();
        btnDominio = new javax.swing.JButton();
        txtAgregar = new javax.swing.JTextField();
        txtEliminar = new javax.swing.JTextField();
        txtEliminar1 = new javax.swing.JTextField();
        txtEliminar2 = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        jbgenerar = new javax.swing.JButton();
        jbrecargar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrando(evt);
            }
        });

        jbeliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbeliminar.setText("Eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbagregar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbagregar.setText("Agregar");
        jbagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbagregarActionPerformed(evt);
            }
        });

        btnletra.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnletra.setText("Buscar Letra");
        btnletra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnletraActionPerformed(evt);
            }
        });

        btnDominio.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        btnDominio.setText("Buscar Dominio");
        btnDominio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDominioActionPerformed(evt);
            }
        });

        txtAgregar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtAgregar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtEliminar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtEliminar1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtEliminar1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtEliminar2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtEliminar2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbgenerar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbgenerar.setText("Generar img");
        jbgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbgenerarActionPerformed(evt);
            }
        });

        jbrecargar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbrecargar.setText("Recargar img");
        jbrecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbrecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jbeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jbagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnletra))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(68, 68, 68)
                            .addComponent(btnDominio))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jbgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbrecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(16, 16, 16)
                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(txtAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbeliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtEliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnletra, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(txtEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(btnDominio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbrecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(lbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed
        // TODO add your handling code here:
//        if(!txtAgregar.getText().equals("")){
//            int x = -1;
//            try{
//                x = Integer.parseInt(txtAgregar.getText());
//            }catch(Exception ex){
//
//            }
//            if(x != -1){
//                RequestBody rb = new FormEncodingBuilder()
//                .add("dato", txtAgregar.getText())
//                .build();
//                String print = Lista.getString("queueCola", rb);
//                //System.out.println(print);
//
//                RequestBody rb2 = new FormEncodingBuilder()
//                .add("dato", "unico")
//                .build();
//                String recorrido = Lista.getString("recorrerCola", rb2);
//                String pathTxt = Metodos.generarTxt("cola", recorrido);
//                pathImg = Metodos.generarImagen(pathTxt, "cola");
//
//                System.out.println(recorrido);
//                JOptionPane.showMessageDialog(null, "valor numerico: "+ txtAgregar.getText());//+ " indice " + print + " agregado");
//            txtAgregar.setText("");
//        }
//        }
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jbagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbagregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbagregarActionPerformed

    private void btnletraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnletraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnletraActionPerformed

    private void btnDominioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDominioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDominioActionPerformed

    private void jbgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbgenerarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbgenerarActionPerformed

    private void jbrecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbrecargarActionPerformed
        // TODO add your handling code here:
        String correo = txtAgregar.getText();
        
        if(!correo.equals("")){
            try{
                String var[] = correo.split("@");
        
                String dato = var[0];
                String dato2 = var[1];
                
                RequestBody rb2 = new FormEncodingBuilder()
                    .add("dato", dato2)
                    .add("dato2", dato)
                    .build();
                
                String recorrido = Lista.getString("agregarDispersa", rb2);
                System.out.println(recorrido);
//                String pathTxt = Metodos.generarTxt("cola", recorrido);
//                pathImg = Metodos.generarImagen(pathTxt, "cola");
            }catch(Exception ex){
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jbrecargarActionPerformed

    private void cerrando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrando
        // TODO add your handling code here:
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_cerrando

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDominio;
    private javax.swing.JButton btnletra;
    private javax.swing.JButton jbagregar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbgenerar;
    private javax.swing.JButton jbrecargar;
    private javax.swing.JLabel lbl1;
    private javax.swing.JTextField txtAgregar;
    private javax.swing.JTextField txtEliminar;
    private javax.swing.JTextField txtEliminar1;
    private javax.swing.JTextField txtEliminar2;
    // End of variables declaration//GEN-END:variables
}
