/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Froms;

import static Froms.Lista.webClient;
import com.squareup.okhttp.FormEncodingBuilder;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.RequestBody;
import com.squareup.okhttp.Response;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonny
 */
public class Pila extends javax.swing.JFrame {
    private Principal p;
    private String pathImg = "";
    /**
     * Creates new form Pila
     * @param p
     */
    public Pila(Principal p) {
        this.p = p;
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pila.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtunico = new javax.swing.JTextField();
        jbpush = new javax.swing.JButton();
        jbpop = new javax.swing.JButton();
        labelReporte = new javax.swing.JLabel();
        recargar = new javax.swing.JButton();
        generar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrando(evt);
            }
        });

        txtunico.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtunico.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jbpush.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbpush.setText("push");
        jbpush.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpushActionPerformed(evt);
            }
        });

        jbpop.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jbpop.setText("pop");
        jbpop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbpopActionPerformed(evt);
            }
        });

        recargar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        recargar.setText("Recargar Img");
        recargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recargarActionPerformed(evt);
            }
        });

        generar.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        generar.setText("generarImg");
        generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtunico, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbpop, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbpush, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(generar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(recargar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)))
                .addComponent(labelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelReporte, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(txtunico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbpush, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jbpop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(recargar)
                .addGap(18, 18, 18)
                .addComponent(generar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbpushActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpushActionPerformed
        // TODO add your handling code here:
        if(!txtunico.getText().equals("")){
            int x = -1;
            try{
                x = Integer.parseInt(txtunico.getText());
            }catch(Exception ex){
                
            }
            if(x != -1){
                RequestBody rb = new FormEncodingBuilder()
                .add("dato", txtunico.getText())
                .build();
                String print = getString("pushPila", rb);
                JOptionPane.showMessageDialog(null, "valor numerico: "+ txtunico.getText());//+ " indice " + print + " agregado");
                txtunico.setText("");
            }
        }
    }//GEN-LAST:event_jbpushActionPerformed

    private void jbpopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbpopActionPerformed
        // TODO add your handling code here:
        RequestBody rb = new FormEncodingBuilder()
        .add("dato", "unico")
        .build();
        String print = getString("popPila", rb);
        System.out.println("DATO POP "+ print);
        //JOptionPane.showMessageDialog(null, "valor numerico "+ txtunico.getText() + " indice " + print + " agregado");
        txtunico.setText("");
    }//GEN-LAST:event_jbpopActionPerformed

    private void cerrando(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrando
        // TODO add your handling code here:
        this.setVisible(false);
        p.setVisible(true);
    }//GEN-LAST:event_cerrando

    private void recargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recargarActionPerformed
        // TODO add your handling code here:
        labelReporte.setIcon(new ImageIcon(Metodos.icono(pathImg, labelReporte.getWidth(), labelReporte.getHeight())));
        labelReporte.setIcon(new ImageIcon(Metodos.icono(pathImg, labelReporte.getWidth(), labelReporte.getHeight())));
    }//GEN-LAST:event_recargarActionPerformed

    private void generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarActionPerformed
        // TODO add your handling code here:
        RequestBody rb2 = new FormEncodingBuilder()
                    .add("dato", "unico")
                    .build();
            String recorrido = Lista.getString("recorrersPila", rb2);
            String pathTxt = Metodos.generarTxt("pila", recorrido);
            pathImg = Metodos.generarImagen(pathTxt, "pila");
            System.out.println(recorrido);
    }//GEN-LAST:event_generarActionPerformed

    public static String getString(String metodo, RequestBody formBody) {

        try {
            URL url = new URL("http://127.0.0.1:5000/" + metodo);
            Request request = new Request.Builder().url(url).post(formBody).build();
            Response response = webClient.newCall(request).execute();//Aqui obtiene la respuesta en dado caso si hayas pues un return en python
            String response_string = response.body().string();//y este seria el string de las respuesta
            return response_string;
        } catch (MalformedURLException ex) {
            //java.util.logging.Logger.getLogger(.log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            //java.util.logging.Logger.getLogger(testwebserver.TestWebServer.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generar;
    private javax.swing.JButton jbpop;
    private javax.swing.JButton jbpush;
    private javax.swing.JLabel labelReporte;
    private javax.swing.JButton recargar;
    private javax.swing.JTextField txtunico;
    // End of variables declaration//GEN-END:variables
}
